# Generated by Django 6.1 on 2026-08-16 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/images/')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('categorie', models.CharField(choices=[('document', 'Document'), ('video', 'Vidéo'), ('image', 'Image'), ('autre', 'Autre')], max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_adhesion', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_attente', 'En attente'), ('bloque', 'Bloqué')], default='en_attente', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_membre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('code_unique', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='certificats/pdfs/')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.formation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='admin_panel.membre')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('type_paiement', models.CharField(choices=[('adhesion', 'Adhésion'), ('formation', 'Frais de formation'), ('don', 'Don')], max_length=20)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='admin_panel.membre')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('progression', models.IntegerField(default=0, help_text='Pourcentage de réalisation (0-100)')),
                ('statut', models.CharField(choices=[('planification', 'Planification'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planification', max_length=20)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
    ]
